"""due_data t0 due_date

Revision ID: 10e8a2968ceb
Revises: b8f67bd0235d
Create Date: 2026-05-15 15:26:47.895784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '10e8a2968ceb'
down_revision: Union[str, Sequence[str], None] = 'b8f67bd0235d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('due_date', sa.DateTime(timezone=True), nullable=True))
    op.drop_column('tasks', 'due_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('due_data', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.drop_column('tasks', 'due_date')
    # ### end Alembic commands ###
