"""extend task collaboration fields

Revision ID: b8f67bd0235d
Revises: 9d4f2c1a8b6e
Create Date: 2026-05-11 16:00:41.017527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision: str = 'b8f67bd0235d'
down_revision: Union[str, Sequence[str], None] = '9d4f2c1a8b6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


task_priority_enum = postgresql.ENUM('low', 'medium', 'high', 'urgent', name='taskpriority', create_type=False)
task_status_enum = postgresql.ENUM('todo', 'in_progress', 'review', 'done', 'canceled', name='taskstatus', create_type=False)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    task_priority_enum.create(bind, checkfirst=True)
    task_status_enum.create(bind, checkfirst=True)

    op.add_column('tasks', sa.Column('priority', task_priority_enum, nullable=True))
    op.add_column('tasks', sa.Column('due_data', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('tasks', 'status',
               existing_type=sa.VARCHAR(length=20),
               type_=task_status_enum,
               existing_nullable=True,
               postgresql_using='status::taskstatus')
    op.create_index(op.f('ix_tasks_priority'), 'tasks', ['priority'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_priority'), table_name='tasks')
    op.alter_column('tasks', 'status',
               existing_type=task_status_enum,
               type_=sa.VARCHAR(length=20),
               existing_nullable=True,
               postgresql_using='status::text')
    op.drop_column('tasks', 'due_data')
    op.drop_column('tasks', 'priority')
    bind = op.get_bind()
    task_priority_enum.drop(bind, checkfirst=True)
    task_status_enum.drop(bind, checkfirst=True)
    # ### end Alembic commands ###
